from pydantic import BaseModel
from typing import Optional


class Document(BaseModel):
    name: Optional[str] = None
    content: str


class Query(BaseModel):
    question: str


class URLQuery(BaseModel):
    url: str

class AutogeneratedDocument(BaseModel):
    id: str
    name: Optional[str] = None
    content: str
